### ISSUE TITLE
Create Hook / Trigger to Send Welcome Email on Sign Up

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-auth#11]
When a new user signs up for the Commons, he or she should receive a welcome email from commons@mla.org.

See mlaa/cbox-mla#209

**Comment by JonathanReeve** [comment]
The ideal way to do this would be to add an admin editable field to the dashboard, maybe in Network Dashboard -> Settings -> Network Settings -> Welcome Email, so that it would be easy to edit this email without getting into the code. But since that would take a long time to implement, it might be easier to just hard-code the email and have it be translatable along with the other strings.

**Comment by terrainsvagues** [comment]
Editing the email would indeed be ideal, especially as many of the links to FAQ / help items will doubtless change once that overhaul is complete. But if it's going to take a long, long, time, then I guess we'll have to go with the bandaid option for now.

**Comment by JonathanReeve** [comment]
I'll try adding the field to the admin area. It might not be too hard, after all.

**Comment by chriszarate** [comment]
There already is such a template in almost the exact place you're talking about (it's "Welcome User Email" instead of "Welcome Email"). It doesn't get sent because we are bypassing WP onboarding entirely. My hope was that we could just call that e-mail routine in this plugin, hopefully just by lifting code from WP core.

**Comment by JonathanReeve** [comment]
I was hoping there might be something like that already in place. I thought that the "Welcome User Email" template is sent out to new users of new sites (judging from its categorization under "New Site Settings"), but this probably also applies to the Commons as a whole, since that may also be considered a child site. This looks like it might be handled by `wpmu_signup_user_notification()`.

**Comment by chriszarate** [comment]
Good point, we'll need to figure that out. The text for the Commons welcome e-mail will need to be different from any e-mails that are triggered when User X is added to Site Y.

**Comment by terrainsvagues** [comment]
Text is trafficking currently.

**Comment by JonathanReeve** [comment]
I added some logging functions to `wp_mail()` to see what emails go out for which actions, and I can't seem to find an action that triggers the email from Dashboard -> Settings -> Network Settings -> New Site Settings -> Welcome User Email, so I'll just try to write a hook to send out this email template, and hope it doesn't affect anything else.

**Comment by JonathanReeve** [comment]
Ok, the function's all set. When a user logs in for the first time, it'll send the email specified in Dashboard -> Settings -> Network Settings -> New Site Settings -> Welcome User Email.

**Comment by terrainsvagues** [comment]
And this will definitely come from commons@mla.org and not wordpress? Can we test it?

**Comment by JonathanReeve** [comment]
It uses the same `wp_mail()` function that other email triggers do, so it should be routed through all the same channels, and come from commons@mla.org. I tested that our SMTP plugin is getting triggered when this happens, and its `from` field is `commons@mla.org`, so we should be good.

**Comment by terrainsvagues** [comment]
One more question then: is it a nice HTML email or an ugly text only one?

**Comment by JonathanReeve** [comment]
It's plain text. It can probably handle HTML, though, so if you want to HTML-ify the text when it comes back from editorial, feel free, and when it's done, I'll run it through a few more tests to make sure it works.
